name: floor_annotation
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  Don't use this package directly. Import the floor package instead.
version: 1.0.0-nullsafety.0
homepage: https://github.com/vitusortner/floor
author: Vitus Ortner <vitusortner.dev@gmail.com>

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety
