name: floor_annotation
description: >
  A supportive SQLite abstraction for your Flutter applications.
  Don't use this package. Import the floor package.
version: 0.3.1
homepage: https://github.com/vitusortner/floor
author: Vitus Ortner <vitusortner.dev@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.6
