name: floor_generator
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the dev dependency.
version: 1.0.0
homepage: https://github.com/vitusortner/floor
author: Vitus Ortner <vitusortner.dev@gmail.com>
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.1.0
  build: ^1.6.3
  build_config: ^0.4.6
  code_builder: ^3.6.0
  collection: ^1.15.0
  floor_annotation:
    path: ../floor_annotation/
  meta: ^1.3.0
  source_gen: ^0.9.10+3

dev_dependencies:
  build_test: ^1.3.7
  dart_style: ^1.3.14
  mockito: ^5.0.0
  path: ^1.8.0
  test: ^1.16.5
  test_cov: ^1.0.1
