name: floor_generator
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  This library is the dev dependency.
version: 0.14.0
homepage: https://github.com/vitusortner/floor
author: Vitus Ortner <vitusortner.dev@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: 0.39.14 # pinned because of https://github.com/dart-lang/build/issues/2763
  build: ^1.2.2
  code_builder: ^3.2.1
  meta: ^1.1.8
  source_gen: ^0.9.4+7
  build_config: ^0.4.1+1
  collection: ^1.14.11
  strings: ^0.1.2
  floor_annotation:
    path: ../floor_annotation/
  sqlparser: ^0.10.1

dev_dependencies:
  test: ^1.11.0
  build_test: ^0.10.12
  path: ^1.6.4
  dart_style: ^1.3.3
  test_cov: ^0.2.1
  mockito: ^4.1.1
