name: floor_generator
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the dev dependency.
version: 1.4.2
homepage: https://pinchbv.github.io/floor/
repository: https://github.com/pinchbv/floor
issue_tracker: https://github.com/pinchbv/floor/issues
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  build_config: ^1.1.1
  code_builder: ^4.10.0
  collection: ^1.18.0
  floor_annotation:
    path: ../floor_annotation
  meta:
  source_gen: ^1.5.0
  strings: ^3.0.0

dev_dependencies:
  build_test: ^2.2.2
  dart_style: ^2.3.4
  mockito: ^5.4.4
  path: ^1.9.0
  pub_semver: ^2.1.4
  test: ^1.25.2
  test_cov:
    git:
      url: https://github.com/dkaera/test_cov
