name: floor_generator
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  This library is the dev dependency.
version: 1.0.0-nullsafety.0
homepage: https://github.com/vitusortner/floor
author: Vitus Ortner <vitusortner.dev@gmail.com>
publish_to: none

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  analyzer: ^0.40.4
  build: ^1.5.0
  build_config: ^0.4.2
  code_builder: ^3.5.0
  collection: ^1.15.0-nullsafety
  dartx: ^0.5.0
  floor_annotation:
    path: ../floor_annotation/
  meta: ^1.2.3
  source_gen: ^0.9.7+1

dev_dependencies:
  build_test: ^1.2.2
  dart_style: ^1.3.7
  mockito: ^4.1.1
  path: ^1.8.0-nullsafety
  test: ^1.16.0-nullsafety
  test_cov: ^0.2.1
