name: floor_generator
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the dev dependency.
version: 0.19.0
homepage: https://github.com/vitusortner/floor
author: Vitus Ortner <vitusortner.dev@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: ^0.41.2
  build: ^1.6.2
  build_config: ^0.4.5
  code_builder: ^3.6.0
  collection: ^1.14.13
  meta: ^1.2.4
  source_gen: ^0.9.10+3
  dartx: ^0.5.0
  floor_annotation:
    path: ../floor_annotation/

dev_dependencies:
  build_test: ^1.3.6
  dart_style: ^1.3.12
  mockito: ^4.1.1
  path: ^1.7.0
  test_cov: ^0.2.1
  test: ^1.15.7
