name: floor_generator
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the dev dependency.
version: 1.1.0
homepage: https://floor.codes
author: Vitus Ortner <vitusortner.dev@gmail.com>
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.2.0
  build: ^2.0.0
  build_config: ^1.0.0
  code_builder: ^4.0.0
  collection: ^1.15.0
  floor_annotation:
    path: ../floor_annotation/
  meta: ^1.3.0
  source_gen: ^1.0.0

dev_dependencies:
  build_test: ^2.1.0
  dart_style: 2.0.0
  path: ^1.8.0
  test: 1.17.1
  test_cov: ^1.0.1
