name: example
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  This is an example on how to use the library.
version: 1.0.0
homepage: https://pinchbv.github.io/floor/
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  floor:
    path: ../floor/
  flutter:
    sdk: flutter
  sqflite: any # This dependency is needed to solve the problem with warning about transitive dependencies

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.8
  floor_generator:
    path: ../floor_generator/
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter