name: example
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  This is an example on how to use the library.
version: 0.1.0
homepage: https://github.com/vitusortner/floor
author: vitusortner

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  floor:
    path: ../floor/
  json_annotation: ^3.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator:
    path: ../floor_generator/
  build_runner: ^1.10.3
  json_serializable: ^3.5.0