name: example
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  This is an example on how to use the library.
version: 1.0.0-nullsafety.1
homepage: https://github.com/vitusortner/floor
author: vitusortner
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  floor:
    path: ../floor/
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.11.5
  floor_generator:
    path: ../floor_generator/
  flutter_test:
    sdk: flutter
