site_name: Floor SQLite
site_description: "Floor - The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications"
site_url: https://pinchbv.github.io/floor/
repo_name: floor
repo_url: https://github.com/pinchbv/floor
edit_uri: edit/develop/docs/

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

theme:
  name: material
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: purple
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: purple
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Inter
    code: Jetbrains Mono
  icon:
    repo: fontawesome/brands/github
    logo: octicons/terminal-24
  favicon: img/favicon.png
  features:
    - navigation.tabs

nav:
  - Home:
    - Welcome: index.md
    - Naming: naming.md
    - Feedback: feedback.md

  - Documentation:
    - Getting Started: getting-started.md
    - Architecture: architecture.md
    - Entities: entities.md
    - Database Views: database-views.md
    - Data Access Objects: daos.md
    - Type Converters: type-converters.md
    - Null Safety: null-safety.md
    - Migrations: migrations.md
    - In Memory Database: in-memory-database.md
    - Initialization Callback: initialization-callback.md
    - Platform Support: platform-support.md
    - Isolates: isolates.md
    - Testing: testing.md
    - Examples: examples.md

  - Changelog: changelog.md
