name: floor
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.1.0
homepage: https://github.com/vitusortner/floor
author: Vitus Ortner <vitusortner.dev@gmail.com>
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  floor_annotation:
    path: ../floor_annotation/
  flutter:
    sdk: flutter
  meta: ^1.3.0
  path: ^1.8.0
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  collection: ^1.15.0
  floor_generator:
    path: ../floor_generator/
  flutter_test:
    sdk: flutter
  matcher: ^0.12.10
  mockito: ^5.0.5
