name: floor
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.4.2
homepage: https://pinchbv.github.io/floor/
repository: https://github.com/pinchbv/floor
issue_tracker: https://github.com/pinchbv/floor/issues
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  collection: ^1.18.0
  floor_annotation:
    path: ../floor_annotation/
  floor_common:
    path: ../floor_common/
  flutter:
    sdk: flutter
  meta:
  path: ^1.9.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  sqlparser: ^0.34.1

dev_dependencies:
  build_runner: ^2.4.8
  floor_generator:
    path: ../floor_generator
  flutter_test:
    sdk: flutter
  matcher: ^0.12.16+1
  mockito: ^5.4.4
  sqflite_common: ^2.5.3