name: floor_common
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.2.0
homepage: https://floor.codes
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  floor_annotation:
    path: ../floor_annotation/
  meta:
  path: ^1.9.0
  sqflite_common: ^2.5.3
  sqlparser: ^0.34.1

dev_dependencies:
  build_runner: ^2.4.8
  collection: ^1.18.0
  floor_generator:
    path: ../floor_generator/
  sqflite_common_ffi: ^2.3.2+1
  test: ^1.25.2
  matcher: ^0.12.16+1
  mockito: ^5.4.4
